Bookyear
LibraryProjectGroup/library-project-backend pull request #106
Opened 2023-02-08 10:45 UTC by Palmitos254

Adds bookyear field into backend

2023-02-08 13:42 UTC, julisod commented
It looks like the conflicts are about formatting, can you run prettier and then commit again?
If you don't have the extension, easiest way to run it would be to type `npm run fmt` in the command line.

This is an understandable conflict since I have forgotten to check that everyone knows to use prettier.
I also changed base branch to main since that's the latest version (this can be discussed on friday but for now the main has all the latest changes) and it'd be good to merge directly into main rn to avoid conflict. And the conflicts don't go away by changing the branch, they're part of the process when working in a team and they have to be resolved.

2023-02-10 09:24 UTC, jord1e requested changes

2023-02-10 09:24 UTC, jord1e commented on sql/01_EfiLibrary.sql
> +  `year` int(5) NOT NULL,
```suggestion
  `year` YEAR NOT NULL,
```

https://dev.mysql.com/doc/refman/5.7/en/year.html

2023-02-10 09:40 UTC, jord1e requested changes

2023-02-10 09:40 UTC, jord1e commented on src/queries/book.ts
>      [book.title, book.author, book.topic, book.isbn, book.location, book.id]
```suggestion
    [book.title, book.author, book.year, book.topic, book.isbn, book.location, book.id]
```

2023-02-10 09:55 UTC, jord1e approved these changes

2023-02-10 11:43 UTC, merged